[functions.analizar-riesgo]
enabled = true
verify_jwt = true                         # ¡Seguridad activada!
import_map = "./functions/analizar-riesgo/deno.json"
entrypoint = "./functions/analizar-riesgo/index.ts"